### ISSUE TITLE
Is it possible to have a good file for testing?

### ISSUE THREAD

**Issue by francescobonesi** [tayler6000/pyVoIP#1]
Hello, I'm having some troubles in using writeAudio function.
Do you have a good file to use or an example on how to send it inside a call?

I have tried this
```
with open(_filename, 'rb') as f:
    _data = f.read()
    call.writeAudio(_data)
```
with a file PCMU 8kHz mono. But this produces a very bad noise in the channel.

Thanks for your help

**Comment by tayler6000** [comment]
Sure thing, I use the following code.

```python
import wave

f = wave.open(_filename, 'rb')
_frames = f.getnframes()
_data = f.readframes(_frames)
f.close()
call.writeAudio(_data)
```

Also, just a tip, the `_frames` variable is good to keep around.  Divided by 8000 (8khz) it will provide the exact length the audio will play.  I usually use it in this way:

```python
from pyVoIP.VoIP import CallState
import time

stop = time.time() + (_frames / 8000)

while time.time() <= stop and call.state == CallState.ANSWERED:
  time.sleep(1)
```

The `time.sleep(1)` is important as it will prevent the CPU core from ramping up.  Hope it helps!  If you have any more problems, please upload some sample code and the audio file you're working with.
