### ISSUE TITLE
How to get caller number?

### ISSUE THREAD

**Issue by Koshkodav** [tayler6000/pyVoIP#104]
I tried to use SIPMessage.resume() in [basic example](https://github.com/tayler6000/pyVoIP#basic-example) for getting caller number but got different errors. Can you point out my mistake? Thank a lot.

**Comment by jrozhon** [comment]
Hi, I am not sure, if I understand correctly. But basically, if you want to access the information from SIP Request that initiated a call, it is accessible via request attribute of a call instance. So, for the basic example from the documentation, you can just change the callback to something like this:

```
def answer(
    call,
):
    try:
        print("Heading: ", call.request.heading)
        print("To header: ", call.request.headers["To"])
        print("From header: ", call.request.headers["From"])
        call.answer()
        call.hangup()
    except InvalidStateError:
        pass
```

**Comment by Koshkodav** [comment]
Thank a lot @jrozhon it works.
