### ISSUE TITLE
Can't get 'write_audio' to work properly...

### ISSUE THREAD

**Issue by TipsTricksMore** [tayler6000/pyVoIP#105]
Hi @tayler6000,

thanks a lot for your great work on this project.

I'm somehow having issues getting the 'Announcement Board'-Example to work.
All my SIP data is correct, and I can answer and end calls without any problem. 
However, a soon as I start to play audio using 'write_audio' it's all very choppy...

My audio file should be encoded correctly... I rechecked that multiple times...
I only changed the SIP data and Audio file from your example code... 

I'm curretnly using:
pyVoIP Version: 1.6.4
Python 3.8

Slightly modified code:
```
from pyVoIP.VoIP import VoIPPhone, InvalidStateError, CallState
import time
import wave


# ACCOUNT DATA:
SIP_IP = 'sip.easybell.de'
SIP_Port = 5060
SIP_Username = 'xxx'
SIP_Password = 'xxx'
myIP = 'xxx.xxx.xxx.xxx'

def answer(call):
    try:
        f = wave.open('AUDIOs/welcome.wav', 'rb')
        frames = f.getnframes()
        data = f.readframes(frames)
        f.close()

        call.answer()
        call.write_audio(data)  # This writes the audio data to the transmit buffer, this must be bytes.

        stop = time.time() + (frames / 8000)  # frames/8000 is the length of the audio in seconds. 8000 is the hertz of PCMU.

        while time.time() <= stop and call.state == CallState.ANSWERED:
            time.sleep(0.1)
        call.hangup()
    except InvalidStateError:
        pass
    except:
        call.hangup()


if __name__ == "__main__":
    phone = VoIPPhone(SIP_IP, SIP_Port, SIP_Username, SIP_Password, myIP=myIP, callCallback=answer)
    phone.start()
    input('Press enter to disable the phone')
    phone.stop()
```

Do you have any idea what could be the issue for choppy audio? 
I already tried using a different internet connection for my computer, but that did not change anything.

Help would be very much appreciated!

Thanks!

**Comment by jrozhon** [comment]
Hi, how do you know that the sound is choppy? Only by listening on the caller side, or by network analyzer as well? I have just ran your code with my recording and development branch of the package (because I am on Asterisk) and sound was clear on every hop of the connection.

Although I am on VPN connection, my stats - jitter, loss, delay are ok. Can you check it the same way just to rule out a network issue?

Regards, J

![pyvoip-choppy_audio_problem](https://user-images.githubusercontent.com/12800857/217073550-685bfbae-9d7c-4fb1-868a-7e9a63dee4bf.png)

**Comment by TipsTricksMore** [comment]
Hi @jrozhon 
thanks for your fast and detailed response. It turned out that my internet connection really was the issue...
I put my code onto a server now, and it works flawless!

However, I can't get DTMF-reading to work... But that's a problem with my SIP-provider, I guess... I'm currently using easybell in Germany and opened a ticket to re-check that.

**Comment by TipsTricksMore** [comment]
Hi @jrozhon
thanks for your fast and detailed response. It turned out that my internet connection really was the issue...
I put my code onto a server now, and it works flawless!

However, I can't get DTMF-reading to work... But that's a problem with my SIP-provider, I guess... I'm currently using easybell in Germany and opened a ticket to re-check that.
I'll open a new issue in case something else is wrong... 

Thanks a lot for your help!

BR
Leo

**Comment by jorgesisco** [comment]
is myIP the phone's server IP?
