### ISSUE TITLE
Capability to transfer a call...

### ISSUE THREAD

**Issue by TipsTricksMore** [tayler6000/pyVoIP#106]
Hey @tayler6000,

is there any way of transferring a call to another number? 

After certain IVR-DTMF-inputs, I want to transfer the calling person to another number. I couldn't find this implementation anywhere...
Is this feature not implemented yet, or did I overlook something? 

If it's not implemented yet: Are you planning on doing so in the near future? I would love to have this function in my code!...

Thanks a lot for your great work!

BR
Leo

**Comment by tayler6000** [comment]
Hi!

No, this is not a feature yet, and it's one I haven't thought of until now.  I'll probably include it in 2.0.0 now that you've brought it up.  Any time I've needed this situation I've either implemented in Asterisk, or just had pyVoIP make a new call and send the data to each other.

**Comment by TipsTricksMore** [comment]
That would be awesome!
I'm currently experimenting with a script that takes the order number of an order from my online-shop and presents the user the status of it.
If the user still wants to speak to a real person, I want to transfer the call afterward... 

Do you have a rough estimate on when you'll release 2.0.0? 

Do you have an example on how to send the data of two calls to each other as workaround?

Thank you!

**Comment by tayler6000** [comment]
There currently is not a release timeline for 2.0.0. As for sending data between two calls:

```py
while call1.state == CallState.ANSWERED and call2.state == CallState.ANSWERED:
    call1.write_audio(call2.read_audio(blocking=False))
    call2.write_audio(call1.read_audio(blocking=False))
```

That should be all you need to do.  Now, there might be some error in it because I just wrote this code in this comment and didn't test it, but it should work.

**Comment by pergolafabio** [comment]
Hey, I'm also interested in this

@TipsTricksMore , can you maybe show me an example script how you have done it? I'm new to this...

My goal, is that this pyvoip registers , when an invite comes in, I want to immediately transfer the call to another sip number , including video..

Is this possible in 2.0? Because making another call in example above, then I will loose the video stream, right?

**Comment by tayler6000** [comment]
> Is this possible in 2.0? Because making another call in example above, then I will loose the video stream, right?

This is correct, you would loose the video stream.  This feature is now added to 2.0.0

**Comment by pergolafabio** [comment]
That's nice !! Is it also possible to transfer before answer?
So A calls to B (pyvoip) , B doesnt pickup, but transfer call to C?

**Comment by tayler6000** [comment]
> That's nice !! Is it also possible to transfer before answer? So A calls to B (pyvoip) , B doesnt pickup, but transfer call to C?

This is not currently possible with pyVoIP alone, but I do know this is possible to configure on the Asterisk/PBX end.

**Comment by pergolafabio** [comment]
Yeah, but I wanted to avoid Asterisk, and use pyvoip as a door intercol solution
