### ISSUE TITLE
Unable to decipher SIP request: OPTIONS 

### ISSUE THREAD

**Issue by lucky-ali** [tayler6000/pyVoIP#126]
Hello, 

I am have setup ViciDial Server on the cloud and added two user agents and i am able to connect via Zoiper softphone. However when i try to connect via the code exmaple i am unable to connect i would really appreicate if anyone can help and guide me to figure out what the issue is. 

I have provided the correct server IP where vicidial is hosted (server="xxx.xx.xxx.xxx")
Also i assume myIP is the IP of my local machine internal network?

<img width="722" alt="image" src="https://user-images.githubusercontent.com/20534354/233225831-711eddd1-85db-4b7c-bb01-afd0cdf33fc1.png">

I keep getting the following error.

![image](https://user-images.githubusercontent.com/20534354/233226350-fe919269-fb82-4b94-9291-4cf03f39f637.png)

**Comment by tayler6000** [comment]
Yes, myIP is the IP address of the local machine.  As for options, you have to use 2.0.0-dev.

**Comment by lucky-ali** [comment]
i am unable to create a working code using 2.0.0-dev

are you able to help ? i am using a vicidial server and have a phone setup on it and able to login to zoiper with it but not via the code. please could you provide a sample example?

**Comment by lucky-ali** [comment]
@tayler6000 please could you check this 
<img width="969" alt="image" src="https://github.com/tayler6000/pyVoIP/assets/20534354/f2774e6a-5d35-426b-b8c5-6e360bef19bc">

`(venv) (base) ali@Alis-Air pythonProject % python main.py                                                                      
2023-05-12 00:40:19 [info     ] Starting up phone.             status=PhoneStatus.INACTIVE
SENT:
REGISTER sip:159.69.114.127:5060 SIP/2.0

Headers:
Via: [{'type': 'SIP/2.0/UDP', 'address': ('0.0.0.0', 5060), 'branch': 'z9hG4bK59df3b4027a44d58a60ba19ea', 'rport': None}]
From: {'raw': '"1003" <sip:1003@0.0.0.0:5060>;tag=52ec560c', 'tag': '52ec560c', 'uri': 'sip:1003@0.0.0.0:5060', 'uri-type': 'sip', 'user': '1003', 'password': '', 'display-name': '1003', 'host': '0.0.0.0', 'port': 5060}
To: {'raw': '"1003" <sip:1003@159.69.114.127:5060>', 'tag': '', 'uri': 'sip:1003@159.69.114.127:5060', 'uri-type': 'sip', 'user': '1003', 'password': '', 'display-name': '1003', 'host': '159.69.114.127', 'port': 5060}
Call-ID: 6b86b273ff34fce19d6b804eff5a3f57@0.0.0.0:5060
CSeq: {'check': 1, 'method': 'REGISTER'}
Contact: {'raw': '<sip:1003@0.0.0.0:5060;transport=UDP>;+sip.instance="<urn:uuid:F94038FA-2EB3-428F-B168-FEBDCBD1EEE6>"', 'tag': '', 'uri': 'sip:1003@0.0.0.0:5060', 'uri-type': 'sip', 'user': '1003', 'password': '', 'display-name': '', 'host': '0.0.0.0', 'port': 5060}
Allow: ['INVITE', 'ACK', 'BYE', 'CANCEL', 'OPTIONS']
Max-Forwards: 70
Allow-Events: org.3gpp.nwinitdereg
User-Agent: pyVoIP 2.0.0
Expires: 120
Content-Length: 0

Body:

Raw:
b'REGISTER sip:159.69.114.127:5060 SIP/2.0\r\nVia: SIP/2.0/UDP 0.0.0.0:5060;branch=z9hG4bK59df3b4027a44d58a60ba19ea;rport\r\nFrom: "1003" <sip:1003@0.0.0.0:5060>;tag=52ec560c\r\nTo: "1003" <sip:1003@159.69.114.127:5060>\r\nCall-ID: 6b86b273ff34fce19d6b804eff5a3f57@0.0.0.0:5060\r\nCSeq: 1 REGISTER\r\nContact: <sip:1003@0.0.0.0:5060;transport=UDP>;+sip.instance="<urn:uuid:F94038FA-2EB3-428F-B168-FEBDCBD1EEE6>"\r\nAllow: INVITE, ACK, BYE, CANCEL, OPTIONS\r\nMax-Forwards: 70\r\nAllow-Events: org.3gpp.nwinitdereg\r\nUser-Agent: pyVoIP 2.0.0\r\nExpires: 120\r\nContent-Length: 0\r\n\r\n'


Received UDP Message:
SIP/2.0 401 Unauthorized

Headers:
Via: [{'type': 'SIP/2.0/UDP', 'address': ('0.0.0.0', 5060), 'branch': 'z9hG4bK59df3b4027a44d58a60ba19ea', 'received': '90.250.162.145', 'rport': 5060}]
From: {'raw': '"1003" <sip:1003@0.0.0.0:5060>;tag=52ec560c', 'tag': '52ec560c', 'uri': 'sip:1003@0.0.0.0:5060', 'uri-type': 'sip', 'user': '1003', 'password': '', 'display-name': '1003', 'host': '0.0.0.0', 'port': 5060}
To: {'raw': '"1003" <sip:1003@159.69.114.127:5060>;tag=as06e98605', 'tag': 'as06e98605', 'uri': 'sip:1003@159.69.114.127:5060', 'uri-type': 'sip', 'user': '1003', 'password': '', 'display-name': '1003', 'host': '159.69.114.127', 'port': 5060}
Call-ID: 6b86b273ff34fce19d6b804eff5a3f57@0.0.0.0:5060
CSeq: {'check': 1, 'method': 'REGISTER'}
Server: Asterisk PBX 13.38.3-vici
Allow: ['INVITE', 'ACK', 'CANCEL', 'OPTIONS', 'BYE', 'REFER', 'SUBSCRIBE', 'NOTIFY', 'INFO', 'PUBLISH', 'MESSAGE']
Supported: ['replaces', 'timer']
WWW-Authenticate: {'header': 'WWW-Authenticate', 'method': 'Digest', 'algorithm': 'MD5', 'realm': 'asterisk', 'nonce': '476a5551'}
Content-Length: 0

Body:

Raw:
b'SIP/2.0 401 Unauthorized\r\nVia: SIP/2.0/UDP 0.0.0.0:5060;branch=z9hG4bK59df3b4027a44d58a60ba19ea;received=90.250.162.145;rport=5060\r\nFrom: "1003" <sip:1003@0.0.0.0:5060>;tag=52ec560c\r\nTo: "1003" <sip:1003@159.69.114.127:5060>;tag=as06e98605\r\nCall-ID: 6b86b273ff34fce19d6b804eff5a3f57@0.0.0.0:5060\r\nCSeq: 1 REGISTER\r\nServer: Asterisk PBX 13.38.3-vici\r\nAllow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE\r\nSupported: replaces, timer\r\nWWW-Authenticate: Digest algorithm=MD5, realm="asterisk", nonce="476a5551"\r\nContent-Length: 0\r\n\r\n'
zsh: segmentation fault  python main.py
(venv) (base) ali@Alis-Air pythonProject % python main.py
2023-05-12 00:43:52 [info     ] Starting up phone.             status=PhoneStatus.INACTIVE
SENT:
REGISTER sip:159.69.114.127:5060 SIP/2.0

Headers:
Via: [{'type': 'SIP/2.0/UDP', 'address': ('0.0.0.0', 5060), 'branch': 'z9hG4bK3fec95a0c1694415b7992cd69', 'rport': None}]
From: {'raw': '"1003" <sip:1003@0.0.0.0:5060>;tag=472ad375', 'tag': '472ad375', 'uri': 'sip:1003@0.0.0.0:5060', 'uri-type': 'sip', 'user': '1003', 'password': '', 'display-name': '1003', 'host': '0.0.0.0', 'port': 5060}
To: {'raw': '"1003" <sip:1003@159.69.114.127:5060>', 'tag': '', 'uri': 'sip:1003@159.69.114.127:5060', 'uri-type': 'sip', 'user': '1003', 'password': '', 'display-name': '1003', 'host': '159.69.114.127', 'port': 5060}
Call-ID: 6b86b273ff34fce19d6b804eff5a3f57@0.0.0.0:5060
CSeq: {'check': 1, 'method': 'REGISTER'}
Contact: {'raw': '<sip:1003@0.0.0.0:5060;transport=UDP>;+sip.instance="<urn:uuid:745F4F4E-EC99-4A4A-B0B2-23783BB95176>"', 'tag': '', 'uri': 'sip:1003@0.0.0.0:5060', 'uri-type': 'sip', 'user': '1003', 'password': '', 'display-name': '', 'host': '0.0.0.0', 'port': 5060}
Allow: ['INVITE', 'ACK', 'BYE', 'CANCEL', 'OPTIONS']
Max-Forwards: 70
Allow-Events: org.3gpp.nwinitdereg
User-Agent: pyVoIP 2.0.0
Expires: 120
Content-Length: 0

Body:

Raw:
b'REGISTER sip:159.69.114.127:5060 SIP/2.0\r\nVia: SIP/2.0/UDP 0.0.0.0:5060;branch=z9hG4bK3fec95a0c1694415b7992cd69;rport\r\nFrom: "1003" <sip:1003@0.0.0.0:5060>;tag=472ad375\r\nTo: "1003" <sip:1003@159.69.114.127:5060>\r\nCall-ID: 6b86b273ff34fce19d6b804eff5a3f57@0.0.0.0:5060\r\nCSeq: 1 REGISTER\r\nContact: <sip:1003@0.0.0.0:5060;transport=UDP>;+sip.instance="<urn:uuid:745F4F4E-EC99-4A4A-B0B2-23783BB95176>"\r\nAllow: INVITE, ACK, BYE, CANCEL, OPTIONS\r\nMax-Forwards: 70\r\nAllow-Events: org.3gpp.nwinitdereg\r\nUser-Agent: pyVoIP 2.0.0\r\nExpires: 120\r\nContent-Length: 0\r\n\r\n'


Received UDP Message:
SIP/2.0 401 Unauthorized

Headers:
Via: [{'type': 'SIP/2.0/UDP', 'address': ('0.0.0.0', 5060), 'branch': 'z9hG4bK3fec95a0c1694415b7992cd69', 'received': '90.250.162.145', 'rport': 5060}]
From: {'raw': '"1003" <sip:1003@0.0.0.0:5060>;tag=472ad375', 'tag': '472ad375', 'uri': 'sip:1003@0.0.0.0:5060', 'uri-type': 'sip', 'user': '1003', 'password': '', 'display-name': '1003', 'host': '0.0.0.0', 'port': 5060}
To: {'raw': '"1003" <sip:1003@159.69.114.127:5060>;tag=as2ddf7258', 'tag': 'as2ddf7258', 'uri': 'sip:1003@159.69.114.127:5060', 'uri-type': 'sip', 'user': '1003', 'password': '', 'display-name': '1003', 'host': '159.69.114.127', 'port': 5060}
Call-ID: 6b86b273ff34fce19d6b804eff5a3f57@0.0.0.0:5060
CSeq: {'check': 1, 'method': 'REGISTER'}
Server: Asterisk PBX 13.38.3-vici
Allow: ['INVITE', 'ACK', 'CANCEL', 'OPTIONS', 'BYE', 'REFER', 'SUBSCRIBE', 'NOTIFY', 'INFO', 'PUBLISH', 'MESSAGE']
Supported: ['replaces', 'timer']
WWW-Authenticate: {'header': 'WWW-Authenticate', 'method': 'Digest', 'algorithm': 'MD5', 'realm': 'asterisk', 'nonce': '74c561bf'}
Content-Length: 0

Body:

Raw:
b'SIP/2.0 401 Unauthorized\r\nVia: SIP/2.0/UDP 0.0.0.0:5060;branch=z9hG4bK3fec95a0c1694415b7992cd69;received=90.250.162.145;rport=5060\r\nFrom: "1003" <sip:1003@0.0.0.0:5060>;tag=472ad375\r\nTo: "1003" <sip:1003@159.69.114.127:5060>;tag=as2ddf7258\r\nCall-ID: 6b86b273ff34fce19d6b804eff5a3f57@0.0.0.0:5060\r\nCSeq: 1 REGISTER\r\nServer: Asterisk PBX 13.38.3-vici\r\nAllow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE\r\nSupported: replaces, timer\r\nWWW-Authenticate: Digest algorithm=MD5, realm="asterisk", nonce="74c561bf"\r\nContent-Length: 0\r\n\r\n'
Traceback (most recent call last):
  File "/Users/ali/Documents/Code/IdrakAI/V4/pythonProject/main.py", line 35, in <module>
    run_phone()
  File "/Users/ali/Documents/Code/IdrakAI/V4/pythonProject/main.py", line 23, in run_phone
    phone.start()
  File "/Users/ali/Documents/Code/IdrakAI/V4/pythonProject/pyVoIP/VoIP.py", line 686, in start
    self.sip.start()
  File "/Users/ali/Documents/Code/IdrakAI/V4/pythonProject/pyVoIP/SIP/client.py", line 190, in start
    self.register()
  File "/Users/ali/Documents/Code/IdrakAI/V4/pythonProject/pyVoIP/SIP/client.py", line 997, in register
    regRequest = self.gen_register(response)
  File "/Users/ali/Documents/Code/IdrakAI/V4/pythonProject/pyVoIP/SIP/client.py", line 543, in gen_register
    regRequest += self.gen_authorization(request)
  File "/Users/ali/Documents/Code/IdrakAI/V4/pythonProject/pyVoIP/SIP/client.py", line 381, in gen_authorization
    digest = self.gen_digest(request)
  File "/Users/ali/Documents/Code/IdrakAI/V4/pythonProject/pyVoIP/SIP/client.py", line 320, in gen_digest
    qop = request.authentication.get("qop", None).pop(0)
AttributeError: 'NoneType' object has no attribute 'pop'
`

**Comment by VadyChel** [comment]
Have the same error. Please help to fix this

**Comment by lucky-ali** [comment]
@VadyChel i had to give up on this as i was unable to fix the issue. Did you manage to get it fixed?
