### ISSUE TITLE
Proposal for branch namings

### ISSUE THREAD

**Issue by Input-BDF** [tayler6000/pyVoIP#13]
To keep a little bit track of branches and what was their purpose (even after merge and delete) I propose prepending thier intend.

So a branch fixing a bug would be named `bugfix/name_of_the_issue`.
A branch dealing with a new feature ends up in `feature/name_of_feature_or_feature_request_issue`

Master should stay master (I dont have to mention^^).

Things like v1.6.0-dev are okay for me but you could work here with tags and leave one branch named `develop`. Think there is no real need to keep version number in development branch name.

**Comment by Input-BDF** [comment]
On thing regarding pull requests. As @tayler6000 is product owner it should remain in your hands to decide whether a request is merged into develop/master or not. Don't wanna be a pirate,  aye P)

**Comment by tayler6000** [comment]
I think I still prefer the version in a development branch, like `v1.6.0-dev`.  In this way, if ever multiple versions are being worked on at the same time, you can distinguish the difference.  It also provides the ability to simply rename the branch to `v1.6.0` after release, then merge to master but keep the `v1.6.0` branch.  Then when v2.0.0 is complete that will be merged to master as well, however, the v1.6.0 branch will remain in case we find a security issue, vulnerability, critical bug fix, etc, that needs to be patched, we can build v1.6.1 right off that branch.

However, with that in mind, it may be better to just have the branch be named `v1.6` and use tags/releases on the branch to signify the patch number.  This is similar to [Python/CPython](https://github.com/python/cpython).

I do agree with the bugfix and feature branch naming.  Perhaps all updates to the software should have an Issue on GitHub tied to it? Like Issue #8 for example?  That way, the implementation of that can just be branch feature/Issue-8, and it would be (in theory) super easy to find if someone forgot to link the pull request to the issue.

Happy to hear your thoughts on all of this!

**Comment by tayler6000** [comment]
> On thing regarding pull requests. As @tayler6000 is product owner it should remain in your hands to decide whether a request is merged into develop/master or not. Don't wanna be a pirate, aye P)

I do appreciate maintaining this right, but for a pull request that I myself make, and assign you as the reviewer, feel free to merge it.  If the pull request was not made by me, then I would like to be the one who merges it after your review to give me a chance to review it as well.
