### ISSUE TITLE
read_audio return nothing

### ISSUE THREAD

**Issue by VadyChel** [tayler6000/pyVoIP#156]
```
    def voip_callback(call: VoIPCall):
        print("CALLBACK STATEE", call.state)
        while call.state == CallState.ANSWERED:
            r = call.read_audio()
            print(r)
            call.write_audio(r)

            time.sleep(0.01)
````

I have this code. When read_audio(blocking=True) while loop is blocked for long time and nothing returned, if read_audio(blocking=False) return always same data `b'\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80\x80'`. write_audio doesn't do anything, I doesn't hear anything on the phone

**Comment by VadyChel** [comment]
Okay, I fix it by replacing rtp client start code with this:
OLD
![photo_2023-06-28_19-13-54](https://github.com/tayler6000/pyVoIP/assets/67959852/3e9321fb-6f20-44ff-ad5a-134f2c932bb8)

NEW
![photo_2023-06-28_19-14-42](https://github.com/tayler6000/pyVoIP/assets/67959852/56ed391c-6af7-4014-9218-e910625cd994)
```
    def start(self) -> None:
        self.sin = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        # Some systems just reply to the port they receive from instead of
        # listening to the SDP.
        self.sout = self.sin
        self.sin.bind((self.in_ip, self.in_port))
        self.sin.setblocking(False)

        r = Timer(0, self.recv)
        r.name = "RTP Receiver"
        r.start()
        t = Timer(0, self.trans)
        t.name = "RTP Transmitter"
        t.start()
```
I take code from main branch

**Comment by oliverguhr** [comment]
Hi, 
I have a similar issue. The "call.read_audio()" blocks and returns nothing. Using "call.read_audio(160,blocking=False))" I get only x80 back. 

I tried this with 1.6.4, 1.6.5 RC1 and with the current git source.
