### ISSUE TITLE
pyVoIP 2.0.0 (Development Branch) Not Working

### ISSUE THREAD

**Issue by tayler6000** [tayler6000/pyVoIP#162]
Currently, the development branch isn't really usable.  This issue is simply for tracking everything wrong with it.  If you run into an error using the development branch, please post it here.  Currently working on trying to get INVITE to work again, but I intend to fix everything that broke with #100

**Comment by hellcatwatermelonfriedchicken** [comment]
#175

**Comment by hellcatwatermelonfriedchicken** [comment]
https://github.com/tayler6000/pyVoIP/issues/174#issuecomment-1713129372
