### ISSUE TITLE
SIPClient.stop() should be called on VoIPPhone.start() failure?

### ISSUE THREAD

**Issue by tayler6000** [tayler6000/pyVoIP#18]
Issue #16 brought up the point that in run time, you must call `SIPClient.stop()` before you can properly call `SIPClient.start()` again.  This makes sense in ever case except in the event of an error on start.  I propose we add `SIPClient.stop()` in the exception handing of `VoIPPhone.start()`.

**Comment by tayler6000** [comment]
Also, might be worth changing `self.NSD` to `False` on init.  Then checking if `self.NSF == False` on `SIPClient.start()` and raising an error if not. I'm thinking `RuntimeError` but I'd check the list of exceptions to see if a better one applies.

**Comment by Input-BDF** [comment]
Also was thinking about adding `SIPClient.stop()` in `VoIPPhone.start()` on fail, but was not shure about. By stopping (resetting) the Phone it made sence in my case so it's a "clear" exit. And I don't know at the moment if it's a good idea to catch an exception on start(), then re-raise cause it should be available outside the VoIPPhone.

**Comment by tayler6000** [comment]
Well by re-raising the exception it is available outside of `VoIPPhone` especially if you just use `raise` without any arguments.  To me it doesn't really make sense you have to stop if you failed to start.

**Comment by Input-BDF** [comment]
Actually your right. This way VoIPPhone also "cleans up" after itself on failure.
