### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by Feuerhamster** [tayler6000/pyVoIP#184]
I was using this library to accept internal phone calls.
Everything is working fine, but I get a lot of deprecation warnings in the terminal every time there is an incoming call.
My phone system is a FritzBox.

Python version: 3.11.0
Library version: 1.6.5

![grafik](https://github.com/tayler6000/pyVoIP/assets/38376566/b0609b60-8dbc-48e1-85ae-f1b019b28d2a)

**Comment by tayler6000** [comment]
Your software is reporting deprecations within the library itself.  These are all resolved in 2.0.0
