### ISSUE TITLE
call forward while currently on call

### ISSUE THREAD

**Issue by BRIDGE-AI** [tayler6000/pyVoIP#207]
Hello,

Can I forward the call while currently on a VoIP call?
(maybe in ANSWER callback function)
I cannot find any resources related this function on v1.6.5 documents.

https://pyvoip.readthedocs.io/en/v1.6.5/SIP.html?highlight=forward

Or do you have any plans to do add this feature?

Thanks you.

@tayler6000

**Comment by tayler6000** [comment]
This feature was added in v2.0.0a1
