### ISSUE TITLE
Register Requests are not passed through NAT

### ISSUE THREAD

**Issue by tayler6000** [tayler6000/pyVoIP#209]
I noticed today that when registering to an external registrar, it is still using the internal IP in the From header because this is not going through NAT.  Need to fix this, and look for any other places this may be happening.

**Comment by key2peace** [comment]
would STUN support be an option?

**Comment by tayler6000** [comment]
@key2peace

It's an interesting idea. Currently, NAT is programmed manually when initializing the `VoIPPhone` through the `NAT` class. See the documentation [here](https://pyvoip.readthedocs.io/en/development/Networking.html#nat). This allows you to use a remote and local hostname if you wish which helps if you happen to have dynamic IP addresses and your IP changes before your Contact URI expires.  I think it would be an honorable mention in the docs on how to use that library to ensure you configure your `VoIPPhone` correctly if we don't end up integrating it.

**Comment by tayler6000** [comment]
Actually, upon looking at the library, it appears it was written for Python 2.7 and has some bugs in Python 3.  It was last release was in 2014 and the last commit was in 2016 with multiple PRs dating back to 2014.  The tags themselves say the code was a beta version. Because of all this, I think it would be unwise to rely on this library.
