### ISSUE TITLE
Enviroment

### ISSUE THREAD

**Issue by xyc0815** [tayler6000/pyVoIP#25]
We I try to use this code with an SIP service from the web, this code is not working. In what an enviroment this client is working?

**Comment by tayler6000** [comment]
This code is tested against Asterisk.  v1.6.0-dev has had a lot of improvements to work with other services as well.  Have you tried using the code from the v1.6.0-dev branch?

**Comment by xyc0815** [comment]
Now I've tried the code v1.6.0 and got the same problem. I use the sip2sip.info service for my tests. Here I've to use a proxy, so I added a proxy element. the register is working. When I try to answer a call I got an error and also got a lost connection error. One thing I also changed is:
```
        elif header=='WWW-Authenticate' or header=="Authorization":
            data = data.replace("Digest", "")
            # add blank to avois the split of qop="auth, auth-int" at this point
            info = data.split(", ")
            header_data = {}
```

**Comment by tayler6000** [comment]
Hmm, that could be the issue.  The code was made working with a PBX, not a proxy server.  That is an improvement we are working on.  I will definitely test on this platform to try and identify the issue. If you feel comfortable posting a packet capture that would be ideal, also have you tried originating calls?

**Comment by xyc0815** [comment]
I've create a fork and added my changes in [https://github.com/xyc0815/pyVoIP/tree/v1.6.0.1-dev](url) and I add here my log file
[sip_log.txt](https://github.com/tayler6000/pyVoIP/files/8104526/sip_log.txt)

**Comment by xyc0815** [comment]
In my for I made a change, so that the proxy worked for me. For that I create a central function send_message and call this from SIPClient and VoIPCall. Now the connection error is gone.
```
    def send_message(self, message):
        debug(f'{self.__class__.__name__}.{inspect.stack()[0][3]} called from '
              f'{inspect.stack()[1][0].f_locals["self"].__class__.__name__}.{inspect.stack()[1][3]} '
              f'--> message sever {(self.proxy if self.proxy else self.server)} port {self.port}'
              f'\n----\n{message}\n----\n')
        self.out.sendto(message.encode('utf8'), ((self.proxy if self.proxy else self.server), self.port))
```

**Comment by xyc0815** [comment]
Hello tayler6000, now my code base [https://github.com/xyc0815/pyVoIP/tree/v1.6.0.1-dev](https://github.com/xyc0815/pyVoIP/tree/v1.6.0.1-dev) works with an external SIP server with proxy and the second phone not in the same local network. In the moment I've a problem with clients using RTP/AVPF. Do you know where to find where to find some informations to implement RTP/AVPF in python?

**Comment by tayler6000** [comment]
@xyc0815 I was looking into that when going through your packets.  I'll look back into it and find some documentation on it.

**Comment by tayler6000** [comment]
Here you are, RFC 4585 https://datatracker.ietf.org/doc/html/rfc4585 @xyc0815

**Comment by xyc0815** [comment]
So now it worked for me to connect a sip2sip.info account as server and generate a call from a linphone client. When a IPv6 connection is in between or the endpoint it's not a problem. I didn't test it when the pyVoIP itself use a IPv6.
@tayler6000 one more question. Is it possible to setup the this client to do bidirectional calls? Do you have an example for this?
