### ISSUE TITLE
Is there any way to make pyVoIP communicate with microsip?

### ISSUE THREAD

**Issue by codemaven0321** [tayler6000/pyVoIP#250]
Now, I'm developing a voip system with pyVoIP. But I have a problem with this. it supports only PCMU 8bit audio stream, but microsip(Windows app) doesn't support 8 bit PCMU. I support 16bit of it. Is there any idea to make good transmission and play audio with microsip?

**Comment by rAcHekLoS** [comment]
MicroSIP supports 8 bit PMCU and PCMA (G.711 A-law/G.711 u-law).
![grafik](https://github.com/tayler6000/pyVoIP/assets/42749713/c0ac0482-d965-41e6-969b-df6ff92a7e61)

**Comment by codemaven0321** [comment]
is it 8 bit audio?

**Comment by rAcHekLoS** [comment]
Yes -> https://en.wikipedia.org/wiki/G.711

**Comment by codemaven0321** [comment]
Thanks for your answer. I tested and it works.
