### ISSUE TITLE
Account's number/URI may be different from the username in authentication.

### ISSUE THREAD

**Issue by tayler6000** [tayler6000/pyVoIP#26]
There are instances where the "number" or URI in the To/From header should be different than what is used in the WWW-Authentication, VoIP and SIP should be edited to handle this.

In general, VoIP and SIP parameters need to be adjusted dramatically to support edge cases, and other routine uses.  For example, Contact likely needs to have a public IP or domain name, however currently it only uses the local binding address.

**Comment by tayler6000** [comment]
This will be a significant change so will wait for 2.0 to implement.

**Comment by bmarwell** [comment]
This is really a blocker. Have you tried to connect anywhere? My router (fritz box) will not accept this either.

**Comment by tayler6000** [comment]
This issue discusses two problems.  One problem is with authentication which was fixed in 0c61424, and the other is with NAT which is also mentioned in #76.  Going forward, I will treat this issue to be specifically about the authentication problem. Since this is done, I will be moving this to the Done status in the project.
