### ISSUE TITLE
My audio stops playing after 5 seconds

### ISSUE THREAD

**Issue by the-master-student** [tayler6000/pyVoIP#266]
Hello everyone,

I have been struggling for a while now with some issues. I have initiate a VoIPPhone, and start a call. I can answer the call on my phone. The caller starts playing an audio file that is 16 seconds long. On my end, I can hear only 5 seconds of them and the sound is cut afterwards. In the write() method I have added some debugging messages and I can still see 160 bytes are read from the wave file. 

Any hint how I can further debug or solve this problem. Thank you so much in advance.

**Comment by the-master-student** [comment]
-- Solved --
PBX Setting

**Comment by hifdv** [comment]
> -- Solved -- PBX Setting

wdym help me
