### ISSUE TITLE
bug - phone.assignedPorts - port allocated but never delete

### ISSUE THREAD

**Issue by t814955** [tayler6000/pyVoIP#27]
Test it with  port range with 1 port only. 2nd call will failed and stuck in the infinite loop

**Comment by tayler6000** [comment]
@Input-BDF Thank you for your insight on this issue!  I think the random.choice is a good idea.  No worries about being away, I've also been pretty busy so I get it.  I'm working on making everything PEP8 Compliant at the moment, but then I will be tackling this issue.
