### ISSUE TITLE
can you tell me about the asterisk version?

### ISSUE THREAD

**Issue by thomasfcw** [tayler6000/pyVoIP#32]
Can you tell me about the asterisk version? thanks.

I using issabel server(Asterisk 11.25.3). the problem is sip is not registering and show this error:

**pyVoIP.SIP.SIPParseError: Unable to decipher SIP request: OPTIONS sip:801@192.168.1.57:5060;transport=UDP SIP/2.0**

**Comment by tayler6000** [comment]
This has been tested against Asterisk 16 and 18.  The most recent versions have only been tested against 18 but should still be compatible with 16.  Hopefully we can outright fix your issue in 1.6 here soon as well.
