### ISSUE TITLE
Hello, I have some questions about your project.

### ISSUE THREAD

**Issue by dvjdjvu** [tayler6000/pyVoIP#33]
1 How can I figured out that call was ended(from on the other side)?
2 How can I sent/read messages to the other side?

Thank you.

**Comment by tayler6000** [comment]
1 `if call.state == CallState.ENDED:`
2 I'm not sure what messages you're talking about.  If you're just talking about sound packets then you can use `call.writeAudio(data)` and `call.readAudio(length=160, blocking=True)`

Please let me know if that doesn't answer your question.

**Comment by dvjdjvu** [comment]
I mean text message.

**Comment by tayler6000** [comment]
PyVoIP currently doesn't support text messaging
