### ISSUE TITLE
Port not released

### ISSUE THREAD

**Issue by centosliuhsuai** [tayler6000/pyVoIP#38]
After each registration, if the port is forcibly stopped and not released, how should this be solved?

**Comment by tayler6000** [comment]
Related to issue #27.

Probably something along the lines of

'''python
try:
    callCallback(...)
except BaseException:
    # Handle
    raise
'''

**Comment by tayler6000** [comment]
This issue was a bit more complicated than my from-memory answer, however, this issue will be resolved as soon as PR #39 is closed.

**Comment by centosliuhsuai** [comment]
I am a beginner. Hope to come up with some simpler cases, such as making phone calls, similar functions, and recording solutions.

**Comment by tayler6000** [comment]
> I am a beginner. Hope to come up with some simpler cases, such as making phone calls, similar functions, and recording solutions.

There is already a function for making phone calls `VoIPPhone.call()`.  I did realize there isn't a way to send DTMF codes yet however.  That may be something a bit easier.  Feel free to make an issue for it and self-assign.  If you do, please make sure to branch off of v1.6.0-dev.

**Comment by centosliuhsuai** [comment]
I probably looked at it. Are you going to have an automatic access phone instead of manual customer service, playing music, and playing DTMO, right?

**Comment by tayler6000** [comment]
I'm not sure what you mean.  Can I have more explanation/context about your question?

**Comment by centosliuhsuai** [comment]
My needs:
I tested the current microphone that played too many recording files, which was very stuttered. I don't know why? There is nothing wrong with the recording itself. Does it have anything to do with my national voice? I am a Chinese.

**Comment by tayler6000** [comment]
I'd have to look at the file and your code but I feel like it's probably an encoding issue with the file.

**Comment by centosliuhsuai** [comment]
I used your demo playback file, directly did not change any operation, using your demo

**Comment by tayler6000** [comment]
This is likely a recording issue then, or possibly a computer issue if your computer is a bit older.

The docs say:

Note: Audio must be in 8 bit, 8000Hz, and Mono/1 channel. You can accomplish this in a free program called [Audacity](https://www.audacityteam.org/). To make an audio recording Mono, go to Tracks > Mix > Mix Stereo Down to Mono. To make an audio recording 8000 Hz, go to Tracks > Resample… and select 8000, then ensure that your ‘Project Rate’ in the bottom left is also set to 8000. To make an audio recording 8 bit, go to File > Export > Export as WAV, then change ‘Save as type:’ to ‘Other uncompressed files’, then set ‘Header:’ to ‘WAV (Microsoft)’, then set the ‘Encoding:’ to ‘Unsigned 8-bit PCM’
