### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by Input-BDF** [tayler6000/pyVoIP#4]
Hej there, 
first of all thx for your work. This was nearly exactly what I needed for my current project.

Cause I needed to adjust indentation according to PEP8 not to make my linter going crazy, it's maybe best if you take a look at my [Fork/Dev-Branch](https://github.com/Input-BDF/pyVoIP/tree/develop) directly before I create a Pull request.

I had to do some more flexible handling on some stuff and a few things I did not quite know why you implemented it this way. Maybe cause of development state or it fullfilled your needs.

Most changes you can get out of commit messages. Most "valuables" I belive are getting rid of your fake requests on (de)register. I currently have no clue why you implemented it this way. I also extended some more reliable message handling e.g. parsing/(re)creation of via headers. 

Tested my stuff with Kamailio and PhonerLite as counterpart. I asume you used Asterisk?

Let my know if a Pull request is okay for you and I will do so.

Cheers
Input

**Comment by tayler6000** [comment]
I pulled your request over to branch v1.6.0-dev.  I commented on most of your commits, however, I intend to open issues for some of the things mentioned that I would like your feedback on; and adjust some of the trivial things.  I will also begin working on the docs.  If you would like to help it would be appreciated.
