### ISSUE TITLE
Unable to decipher SIP request: OPTIONS sip:555@192.168.30.27:5060;transport=UDP SIP/2.0

### ISSUE THREAD

**Issue by yTI0r** [tayler6000/pyVoIP#46]
using: pyVoIP     1.5.5.post1

Have a error: "Unable to decipher SIP request: OPTIONS sip:555@192.168.30.27:5060;transport=UDP SIP/2.0"

it's appear on regRequest:
> 'REGISTER sip:pbx.samaragips.adm SIP/2.0\r\nVia: SIP/2.0/UDP 192.168.30.27:5060\r\nMax-Forwards: 70\r\nContact: <sip:555@192.168.30.27:5060;transport=UDP>\r\nTo: <sip:555@pbx.samaragips.adm;transport=UDP>\r\nFrom: <sip:555@pbx.samaragips.adm;transport=UDP>;tag=7c979330\r\nCall-ID: 6b86b273ff34fce19d6b804eff5a3f57@192.168.30.27:5060\r\nCSeq: 2 REGISTER\r\nExpires: 300\r\nAllow: INVITE, ACK, BYE\r\nUser-Agent: pyVoIP 1.5.5\r\nAuthorization: Digest username="555",realm="asterisk",nonce="1a99d521",uri="sip:pbx.samaragips.adm;transport=UDP",response="650f7a02b2eef76d267ee6bbe01e5b83",algorithm=MD5\r\nContent-Length: 0\r\n\r\n'

then parsing this data (responce):
> b'OPTIONS sip:555@192.168.30.27:5060;transport=UDP SIP/2.0\r\nVia: SIP/2.0/UDP 192.168.55.2:5060;branch=z9hG4bK607c74c7\r\nMax-Forwards: 70\r\nFrom: "asterisk" <sip:asterisk@192.168.55.2>;tag=as23df123d\r\nTo: <sip:555@192.168.30.27:5060;transport=UDP>\r\nContact: <sip:asterisk@192.168.55.2:5060>\r\nCall-ID: 77a8c07619d663295eb4b1ad24645eea@192.168.55.2:5060\r\nCSeq: 102 OPTIONS\r\nUser-Agent: Asterisk PBX 13.9.1\r\nDate: Tue, 19 Apr 2022 08:53:57 GMT\r\nAllow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE\r\nSupported: replaces, timer\r\nContent-Length: 0\r\n\r\n'

**Comment by yTI0r** [comment]
[RFC 3261](http://www.ietf.org/rfc/rfc3261.txt)
>  The SIP method OPTIONS allows a UA to query another UA or a proxy
   server as to its capabilities.  This allows a client to discover
   information about the supported methods, content types, extensions,
   codecs, etc. without "ringing" the other party.  For example, before
   a client inserts a Require header field into an INVITE listing an
   option that it is not certain the destination UAS supports, the
   client can query the destination UAS with an OPTIONS to see if this
   option is returned in a Supported header field.  All UAs **MUST** support
   the OPTIONS method.

**Comment by romjer17** [comment]
I also have the same problem with pyVoip 1.5.4 + kamailio.

**Comment by panosdim** [comment]
I also have the same problem

**Comment by yTI0r** [comment]
> This is a problem with your SIP server, PyVoIP clearly states what requests it can handle and OPTIONS isn't one of them. Your SIP Server disregards that however. I would check your SIP Server docs to see if sending OPTIONS is able to be disabled.

Problem appears whith SIP server `asterisk v13`. But `pjsua2` work normal whith that server. May be problem not in server?

**Comment by yTI0r** [comment]
`1.6.0-dev` on same server (asterisk v13) give another error:
```
Invalid Username or Password for SIP server pbx.adm:5060
  File "/home/user/projects/calls/pyvoip.py", line 28, in <module>
    phone.start()
```

**Comment by yTI0r** [comment]
In version 1.6 error message disappear so  this issue should be closed.

**Comment by uhwf91p** [comment]
> In version 1.6 error message disappear so this issue should be closed.

pyVoIP version 1.6.8, MikoPBX server. There is error yet: "Error on header parsing: Unable to decipher SIP request: OPTIONS sip:111@10.10.1.2:5060 SIP/2.0"
