### ISSUE TITLE
Some issue about example

### ISSUE THREAD

**Issue by data1456** [tayler6000/pyVoIP#50]
When I run the example, it doesn't run successfully. The server keeps sending me invite packets. When creating an RTPclient, the value of TransmitType cannot be found.Can you give me some suggestions?I receive no error when I run the code.

**Comment by MuriloBianco** [comment]
HI, try it on 3.7+!

Change VoIP.py

it
#self.RTPClients.append(RTP.RTPClient(codecs, self.myIP, port, request.body['c'][ii]['address'], i['port']+ii, request.body['a']['transmit_type'], dtmf=self.dtmfCallback)) #TODO: Check IPv4/IPv6

to it
self.RTPClients.append(RTP.RTPClient(codecs, self.myIP, port, request.body['c'][ii]['address'], i['port']+ii, request.body['a'].get('transmit_type', 'sendrecv'), dtmf=self.dtmfCallback)) #TODO: Check IPv4/IPv6


change it in all transmit_type access

**Comment by MuriloBianco** [comment]
Hi Tayler :) Ok, i will! Tks for this project!

**Comment by tayler6000** [comment]
It may still need this patch in 1.6, `call.readAudio` is deprecated but should still work.  Make sure to switch to `call.read_audio()`
