### ISSUE TITLE
issue with the register()

### ISSUE THREAD

**Issue by quanggdungg0609** [tayler6000/pyVoIP#52]
i use the code in exemple and changed some paremeter for my sip server but i have the problem like this:
![error](https://user-images.githubusercontent.com/98978416/165930082-9930f0dc-7bd4-449b-8bb7-58c0309a3fe8.png)
and what i changed in the paremeter is:
`phone=VoIPPhone("pbx4.lanestel.net",5061,"8810","65w451#02k",callCallback=answer)`

**Comment by GataullinRR** [comment]
Try to add `myIP="0.0.0.0"` parameter. In my case it helped to resolve this problem
