### ISSUE TITLE
readAudio only returns data for the first seconds

### ISSUE THREAD

**Issue by MoritzVenus** [tayler6000/pyVoIP#53]
Hi, 

I am trying to record an incoming/outgoing call.
I have the issue, that the function call.readAudio(length=160, blocking=True) only returns data within the first few seconds of an ongoing call.

This is what i tried:

```
bytesArray = bytearray(b'')
time.sleep(3)
while call.state == CallState.ANSWERED:
  bytesString = call.readAudio(length=160, blocking=True)
  bytesArray.extend(bytearray(bytesString))
```

For first 1-2 seconds it works fine, after that its just stuck at call.readAudio and it doesn't return any more data. If i set blocking=False it will just continue to send empty packets. My expectation was, that readAudio always returns the last 160 bytes.

**Comment by gn0m3r4l** [comment]
Even calling "readAudio" once with different "length" values does not provide the expected result

**Comment by tayler6000** [comment]
@MoritzVenus I can't say for sure, but it sounds like the call is being re-negotiated after a few seconds and failing.  It's hard to know for sure without a packet capture however.  What PBX are you using?

**Comment by MoritzVenus** [comment]
> 

Thanks for  the reply. Currently i am using asterisk 16 on an ubuntu 20.04 system. 

If i am doing a call between other SIP clients (micro SIP for example), i dont have any issues. Those calls work perfectly fine.

**Comment by MoritzVenus** [comment]
Figured out, that it doesn't work while `nat=yes` is set in the sip.conf of asterisk. Unfortunately i would need to use this option. 
While `nat=no` it just works fine

**Comment by nikolabura** [comment]
Had this same issue in Asterisk with pjsip. It does seem to be a renegotiation thing. My particular problem was that I had `rtp_symmetric=yes` on the endpoint in `pjsip.conf`. I set it to `rtp_symmetric=no` (which is the default, so just removing that line also worked) and now audio flows fine.

That said, I am only connecting to localhost, no NAT or anything

**Comment by tayler6000** [comment]
In pjsip `direct_media=no` works for me to fix this issue.  In sip I believe it's just `directmedia=no`.

**Comment by otoxteam** [comment]
My PBX is asterisk 18 , and i added `nat=no` now it is working fine
