### ISSUE TITLE
Param "myIp" without internal IP

### ISSUE THREAD

**Issue by gn0m3r4l** [tayler6000/pyVoIP#58]
Hi,

hoiw can I create an instance of VoIPPhone without an internal IP? My system usess a LTE modem to access the internet. I can reach my asterisk server but do not have an internal IP (except for 127.0.0.1 - which does not work)

Greetings,
Daniel

**Comment by gn0m3r4l** [comment]
Manually setting it to 0.0.0.0 did the thing. Contrary to my expectation, leaving out the param does not behave the same as setting it to this IP.

My misunderstanding or a bug?

**Comment by tayler6000** [comment]
> Manually setting it to 0.0.0.0 did the thing. Contrary to my expectation, leaving out the param does not behave the same as setting it to this IP.
> 
> My misunderstanding or a bug?

Weird implementation on my part.  In 1.5 it checks to see the computer's host name and then attempts to resolve it to get the IP, which really only works if your computer is a server machine.  In 1.6 it just binds to 0.0.0.0.
