### ISSUE TITLE
Peer to Peer calls support

### ISSUE THREAD

**Issue by balloob** [tayler6000/pyVoIP#60]
**Context**
I create [Home Assistant](https://www.home-assistant.io) (@home-assistant); a privacy focused open-source home automation platform. One of the things that people always want is a locally working voice assistant. Instead of an always listening microphone I have the idea to use phones. You don't need hot word detection or always listening microphones, instead you pick up the phone and say what you want.

I have a Grandstream HT801 that translates a phone into SIP. In the past I had it working on Python 2 with a package called `linphone`, but that package is no longer maintained and it wasn't pure Python so I shelved the idea.

But now I stumbled upon `pyVoIP` and it has given me hope that this could be the key to reviving this project. I've been playing with it today and I ran into the fact that PyVoIP does not support mimicking a SIP server to allow "peer 2 peer" calls (not sure what correct terminology is). 

I tried stubbing out the `register()` call but that prevents invites from being responded 🙃

The reason I want peer to peer and not use something like Asterisk is because it would increase the users effort to get started.

**Questions**

1. Could peer to peer calls be supported with the current architecture of `pyVoIP`?
1. If yes, is this a feature that would fit in `pyVoIP` or would it better be created as a different package?
1. I am myself very limited in time due to my other open source work. Would there be anyone that could be paid to work on this?

**Comment by tayler6000** [comment]
1. P2P calling is not currently supported with pyVoIP.

2. P2P support I think is a fine feature for pyVoIP.

3. Currently I've also diverted most of my time to other projects due to budget constraints.  However if you are interested in being a pyVoIP sponsor I would be more than happy to redirect time back into development on this project.

**Comment by tayler6000** [comment]
> I am myself very limited in time due to my other open source work. Would there be anyone that could be paid to work on this?

Feel free to email me at [taylerporter@gmail.com](mailto:taylerporter@gmail.com) if you would like to work out sponsorship details.

**Comment by tayler6000** [comment]
The feature/Add-TLS branch is now capable of receiving direct IP (P2P) calls,  It cannot make them yet, and you will still have to `stub out` the register, but this should be enough to begin development on your project at least.
