### ISSUE TITLE
Incompatibility whith Python 3.6.8 of pyVoIP-1.6.0.dev0

### ISSUE THREAD

**Issue by yTI0r** [tayler6000/pyVoIP#63]
When run pyVoIP-1.6.0.dev0 on Python 3.6.8 get error:
```
Traceback (most recent call last):
  File "/home/user/projects/calls/pyvoip.py", line 1, in <module>
    from pyVoIP.VoIP import VoIPPhone, InvalidStateError, CallState
  File "<fstring>", line 1
    (call_id=)
            ^
SyntaxError: invalid syntax
```
On Python 3.10.4 - goes normal.

Problem whith f strings at VoIP.py  on lines 756 and 762
```
                    debug(f"{call_id=} {self.calls=}")
```
and 
```
                    debug(f"{thread=} {self.threadLookup=}")
```
Pylance message: Unexpected token at end of expression

May be you need add correct `python_requires='>` in `setup.py` or fix compatibility whith python 3.6

**Comment by tayler6000** [comment]
Thank you for your issue! I had made the decision that pyVoIP would support the oldest version of Python being supported/maintained. Python 3.6 has reached end of life and is no longer supported by Python itself. (See [PEP 0494](https://peps.python.org/pep-0494/)).  Python 3.7 does support f-strings, and this should resolve your error.  Python 3.7 is still maintained according to [PEP 537](https://peps.python.org/pep-0537/).  Apologies, I did not realize setup.py didn't reflect that.  I will make sure to update it.

**Comment by tayler6000** [comment]
It is my policy that pyVoIP supports the minimum version being maintained by Python itself, which is Python 3.7.  I thought `f"{var=}"` was a Python 3.7 feature but it is apparently Python 3.8.  I've removed these instances.  And since the software works on 3.6 anyways, I've left `setup.py` the same.  This issue is now resolved.
