### ISSUE TITLE
new register always return invalid pass

### ISSUE THREAD

**Issue by MuriloBianco** [tayler6000/pyVoIP#65]
Tayler, im trying to use new version... But alway return invalid pass...
looking at my asterisk the record gets there normally

Any ideia?

**Comment by tayler6000** [comment]
What asterisk version are you using?  And are you using sip.conf or pjsip.conf?

**Comment by yTI0r** [comment]
Have same problem it's linked with #66 but it's not a single reason. 
I locally fixed `realm` issue, but problem with "Invalid Username or Password" don't go away.

**Comment by TecDroiD** [comment]
hi, I also got an invalid pass while trying to connect my fritz box.. any idea?

**Comment by yTI0r** [comment]
@TecDroiD 
> This is the realm it finds: having realm, "fritz.box", " having nonce, "78B29326485EAE52"
> 
> so for some reason, your realm isn't parsed correctly. maybe this helps? Sadly, this bug is a blocker :(

this part of bug is exactly #66 and #67 now fixing it (after your comments and new commit).
