### ISSUE TITLE
Wrong realm value in SIPMessage while parsing WWW-Authenticate header

### ISSUE THREAD

**Issue by yTI0r** [tayler6000/pyVoIP#66]
pyVoIP-1.6.0
Server: Asterisk PBX 16.28.0
python 3.6.8

I found mistake in SIP.py -> class `SIPMessage` -> `parse_header` 
on steep 'header == "WWW-Authenticate"' and variable `data` have value like this:
`Digest algorithm=MD5, realm="asterisk", nonce="45f77cee"`

after line 461 variable `row_data` will have this values:
```
0:'MD5, '
1:'asterisk", '
2:'45f77cee'
```
as result `self.authentication` and `self.headers['WWW-Authenticate']` wil have a wrong value of `realm` = `asterisk", ` instead `asterisk`.

`realm` - is used in digest procedure, wrong value of it wil cause unable to authenticate on server.

**Comment by yTI0r** [comment]
This is due to the wrong regex pattern in file SIP.py line 344
```
        self.auth_match = re.compile(",?[a-zA-Z0-9]*=")
```
good pattern may be `,?[a-zA-Z0-9 ]*=` or `,? ?[a-zA-Z0-9]*=`
or use different patters for split and match.

**Comment by tayler6000** [comment]
@yTI0r can you make this a PR so you can get credit
