### ISSUE TITLE
Help. Doesn't work radius authorization // call hang up after 32 sec

### ISSUE THREAD

**Issue by Astartoo** [tayler6000/pyVoIP#72]
Hello. My asterisk sip server works with kamailio, I connect via a domain (for example, sip.server.com), my authorization occurs through a radius, and not only during Register, but also during an Invite. 
In order to pass the radius authorization, I need in:

SIP.py -> gen_invite() -> 
`f"From: <sip:{self.username}@{self.myIP}>;tag={tag}\r\n"` 
replace
`f"From: <sip:{self.username}@{self.server}>;tag={tag}\r\n"`

Thus, the authorization passes, but that the incoming/outgoing call ends after 32 seconds, as I understand it, ASK's do not reach.
I would like to ask for your help in solving this problem.
And i have problem with massage OPTIONS for pinger.

**Comment by tayler6000** [comment]
Unfortunately, I don't understand to well what's going on here, however perhaps your calls are ending due to options not working right? That would be a weird setup but to each their own.  I've added OPTIONS support in 2.0-dev so maybe that will work for you? #73
