### ISSUE TITLE
VoIPPhone Class a status

### ISSUE THREAD

**Issue by Input-BDF** [tayler6000/pyVoIP#8]
With the thought "pyVoIP as an API" VoIPPhone class should be able to inform about its current state.

Suggestion:
```
        INACTIVE = 0, 'inactive', ''
        WAIT = 1, 'waiting', ''
        CONNECTED = 2, 'connected', ''
        CLOSING = 3 , 'closing', ''
        FAILED = 4 , 'failed', ''
```

**Comment by tayler6000** [comment]
I like the idea.  What are your thoughts behind each status?  I'm imagining something along the lines of:
```python
from enum import Enum

class PhoneState(Enum):
    INACTIVE = 'inactive'
    REGISTERING = 'registering'
    REGISTERED = 'registered'
    FAILED = 'failed'
```
`INACTIVE` being the initialized state, before `VoIPPhone.start()`, and after `VoIPPhone.stop()`.
`REGISTERING` being whenever `VoIPPhone` is registering, i.e. after `VoIPPhone.start()` or on registration expiring.
`REGISTERED` being whenever `VoIPPhone` is registered and ready for use.
`FAILED` being whenever `VoIPPhone` registration failed, or cannot even connect to the server, etc.

**Comment by Input-BDF** [comment]
Your terms are more fitting. Stages as your wrote. Maybe also `DEREGISTERING` before `VoipPhone.stop()`. This was my thought of closing. So you know the state there if deregister takes a while and you could already block incoming calls in this stage or what ever you want to do^^

**Comment by tayler6000** [comment]
I agree. I wasn't sure whether or not to include `DEREGISTERING`.  Deregistering itself doesn't take too long, however `VoIPPhone.stop()` also hangs up all active calls and does a few more cleanup things as well.  Altogether, it could take a variable amount of time.  So I think a `DEREGISTERING` value would be appropriate.
