### ISSUE TITLE
Invite method leave "self.recvLock" in Locked state

### ISSUE THREAD

**Issue by SEIDO-JP** [tayler6000/pyVoIP#94]
Hi, 

In [SIP.py](https://github.com/tayler6000/pyVoIP/blob/87e8d5077c42d09cafc69d8c0c54fc6729a3e0c5/pyVoIP/SIP.py#L1575) file We have this situation: 

```C
def invite(
        self,
        number: str,
        ms: Dict[int, Dict[str, "RTP.PayloadType"]],
        sendtype: "RTP.TransmitType",
    ) -> Tuple[SIPMessage, str, int]:
(...)
        self.recvLock.acquire()
(...)
        if response.status == SIPStatus(100) or response.status == SIPStatus(
            180
        ):
            return SIPMessage(invite.encode("utf8")), call_id, sess_id
```
So, after `response.status == SIPStatus(100)` from SIP Proxy Server this `self.recvLock` stay in Locked state. 
Shouldn't this lock be released before return from `Invite` method? 
Because now, when this situation occur (which is normal after every calling e.g. through Kamailio SIP Server) any new message cannot be received in `def recv(self)` (SIP.py) method -> this method/Thread stuck while waiting for `self.recvLock` to be released. 

Thanks for answer.

**Comment by tayler6000** [comment]
Thank you for the report, this has been patched.
